version: '3.4'

services:
  basewebapi:
    image: basewebapi:latest
    build:
      context: .
      dockerfile: BaseWebApi/Dockerfile
    environment:
      #loki: http://loki:3100
      - REDISCONNECTION=redis
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7031
      - DOCKER_DB_Host=db
    ports:
      - "7031:7031"
    links:
      - redis
      - db
    depends_on:
      - db
      - redis
      - loki

  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3100/ready
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s

  grafana:
    container_name: grafana
    image:  grafana/grafana:master
    depends_on:
      - loki
    ports:
      - "3000:3000" 
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: postgresql
    # connect this container to the user-defined network my-network
    volumes:
      - ./data/db:/var/lib/postgresql/data
    configs:
      - /etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  db-volume:
    