apiVersion: v1
kind: PersistentVolume
metadata:
  name: productwebapi-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/var/lib/postgresql/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productwebapi-postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productwebapi-postgres
  labels:
    app: productwebapi-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productwebapi-postgres
  template:
    metadata:
      labels:
        app: productwebapi-postgres
    spec:
      volumes:
        - name: productwebapi-postgres-pv-storage
          persistentVolumeClaim:
            claimName: productwebapi-postgres-pvc
      containers:
        - name: productwebapi-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:Ingrss
              cpu: 200m
              memory: 200Mi
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: productwebapi-postgres-pv-storage

---

apiVersion: v1
kind: Service
metadata:
  name: productwebapi-postgres-service
spec:
  type: ClusterIP
  ports:
    - name: "productwebapi-postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: productwebapi-postgres
 