version: "3.2"
services:
  some-rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - common_network
    
  networks:
    common_network:
      driver: bridge  
