version: '3.4'

services:
  ProductWebApi:
    image: productwebapi:1.0.0
    build:
      context: .
    environment:
        LOKI_CONNECTION: http://loki:3100
        LOKI_USER_NAME: admin
        LOKI_PASSWORD: admin
        REDIS_CONNECTION: redis:6379
        IS_LOKI_GRAF: 'false'
        USE_CACHE: 'true'
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://+:80
        DB_CONNECTION: Host=postgresql;Database=productdb;Port=5432;username=postgres;password=postgres
        CONTAINER_RUN: 'true'
        RABBIT_HOST_NAME: rabbitmq
        RABBIT_QUE_NAME: order
        RABBIT_USER_NAME: guest
        RABBIT_PASSWORD: guest
        RABBIT_PORT: 5672
        SECURITY_KEY: order
        VALID_ISSUER: order
        EXPIRY_IN_MINUTES: 60
        RABBIT_EXCHANGE_NAME:
        USE_MESSAGE_BROKER: 'true'
    ports:
        - "8085:80"
    depends_on:
      postgresql:
          condition: service_started
      redis:
          condition: service_started
      loki:
          condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - rabbitmq_go_net
        
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
       - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3100/ready 
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    depends_on:
        - loki
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - rabbitmq_go_net
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    container_name: postgresql
  # connect this container to the user-defined network my-network
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge