// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storage.AppStorage;

#nullable disable

namespace AppStorage.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240408053440_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Base.DataBase.Entities.CameraModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CameraModules");
                });

            modelBuilder.Entity("Core.Base.DataBase.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderPayloadId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Core.Base.DataBase.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72331b12-2724-4faa-9b57-5e6f8fbd8836"),
                            Description = "Description of BestStuff",
                            Name = "BestStuff"
                        },
                        new
                        {
                            Id = new Guid("d32d61b8-85da-45dd-8e0f-b1bceefcf9ef"),
                            Description = "Description of Lolly",
                            Name = "Lolly"
                        },
                        new
                        {
                            Id = new Guid("11d48f9a-95ee-42f4-b46c-e0cd2e8fab4c"),
                            Description = "Description of Candy",
                            Name = "Candy"
                        },
                        new
                        {
                            Id = new Guid("8df1d7b2-e3b4-457d-a5ef-fdcdad315ce2"),
                            Description = "Description of PicksSexoMGLofty",
                            Name = "PicksSexoMGLofty"
                        },
                        new
                        {
                            Id = new Guid("2c41064b-3cc8-442e-8645-1c577412faf5"),
                            Description = "Description of Toffy",
                            Name = "Toffy"
                        },
                        new
                        {
                            Id = new Guid("ab074b32-f399-4609-a6f9-c67916022763"),
                            Description = "Description of Fuckas",
                            Name = "Fuckas"
                        },
                        new
                        {
                            Id = new Guid("e0c519a0-0bfd-4a7b-b879-a5cfe8942655"),
                            Description = "Description of Grep",
                            Name = "Grep"
                        });
                });

            modelBuilder.Entity("Core.Base.DataBase.Entities.ShipmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
