// <auto-generated />
using System;
using Data.IdentityDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityDb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240609092540_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Auh.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AmountOfPoints")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "696d4813-0633-4d12-b9c2-d18c013c66ff",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "1863d7f6-88d2-47d7-aec4-8ef8e9adbd32",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-020@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-0",
                            PasswordHash = "AQAAAAIAAYagAAAAEIvIoI4x15GZ8vTBji0CoVcKHrslfHzOIp57PbZRbyAn46aoj+N5KwDVnkFPPmyqZQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "397921cf-9d3c-4aa6-abb8-ff2f216118a3",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-0"
                        },
                        new
                        {
                            Id = "7dd506f9-90d1-442f-bc9b-9c38fef8a2b6",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "f964d5d5-e00d-4f7e-9472-bc7b51e7b32e",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-120@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-1",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ5bt8m2maoCL7Win3VbRctC3Tj255MiBUNSdILGspt7NSFn8OVk1uxV+15WMUJM4A==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "2256e0f7-bbea-46c5-a6f3-a9d2a21565a4",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-1"
                        },
                        new
                        {
                            Id = "bdc4cbd4-6592-4700-b731-15d28f998f7d",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "b5651476-7cb2-4d65-87fd-17baae56cebc",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-220@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-2",
                            PasswordHash = "AQAAAAIAAYagAAAAEBEH/hqM3PtSAjdh6250S/9ZpRp9rAOXdf3tndJA9m/Luhe5/ujMg+VB18+l1KbSuw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "3700f1ed-c011-462f-8976-9efabb01fd58",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-2"
                        },
                        new
                        {
                            Id = "7232a042-1047-42fd-96ba-c72aed57e2ae",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "093a374e-26ef-4834-8224-80c08fa1dd73",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-320@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-3",
                            PasswordHash = "AQAAAAIAAYagAAAAEHVmbp7zOTFCuRTcmKTswrC77ixLt0MCDyIbnhubzpvvu9HAba+bDHKkkvBriPuwWQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "ef368dba-be4d-4a4c-a011-d2ae0bb7948f",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-3"
                        },
                        new
                        {
                            Id = "40677c08-c27d-45ee-8c11-2887d7bc13b7",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "55d5d266-d4c8-4978-8ee2-9d8ce34e6f4e",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-420@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-4",
                            PasswordHash = "AQAAAAIAAYagAAAAEAeqgM75UI1ncUgP7A0RkIQlAT2psLr+d1JQqJLQPjJOVhOqYSW6eiDlwomriSCL0g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "791c3f03-9363-48ef-8819-80c59d784650",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-4"
                        },
                        new
                        {
                            Id = "18523064-eb41-4a03-9400-70ff589137de",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "65cecb2f-c64b-4a50-83f2-597ae50b07f9",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-520@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-5",
                            PasswordHash = "AQAAAAIAAYagAAAAECd/ezvuvJcOKGSB1v3oi7g453Khl2h761dXdDIjJp4iwrKoF/d7pgZec45rMF8QoQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "be968591-f8d6-4d10-bc90-2928902b4e68",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-5"
                        },
                        new
                        {
                            Id = "3e43fb1f-0f56-4495-8d4c-25e2afe44b53",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "7ee35819-fb1b-4e44-8d85-b6b7fa628586",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-620@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-6",
                            PasswordHash = "AQAAAAIAAYagAAAAEMZ7hVw0K91UvDqmlk4M3WrY1ULsKadwp0RIomgcd76PF+DFCFt9/2YrNegeR5sO9g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "e3398ca4-0a98-41b2-85c6-253cf3fd59ae",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-6"
                        },
                        new
                        {
                            Id = "1281817d-a915-4a2b-823f-54f566386052",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "11a0a614-b907-4650-91fb-a447d1ebde21",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-720@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-7",
                            PasswordHash = "AQAAAAIAAYagAAAAELyuvgkj6YO0Sz5i1E3xpesVaJclahg3FwPNAdevDimWzT6/Zbm58vb4527NF9zMRA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "37c07a7d-6362-47d9-98d6-9c0b218eb158",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-7"
                        },
                        new
                        {
                            Id = "83e22dfe-e470-44aa-9502-6925be3633f2",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "c318e59e-5a51-40bf-b364-a3e9ca95a8f3",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-820@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-8",
                            PasswordHash = "AQAAAAIAAYagAAAAEFuxenj2WiKBfoBvkyqo6xFWc/COjptwB44hYX+UnHaMGh50r16qCNbVNScbb9ZRtg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "5a856ad0-06ee-4dbd-9736-cdd4f876ed75",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-8"
                        },
                        new
                        {
                            Id = "3ed8231c-9dca-4371-b091-a40ab198492d",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "2b712b3b-039a-4b56-b8cb-d14e608ac3ed",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-920@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-9",
                            PasswordHash = "AQAAAAIAAYagAAAAEBw/6bthp2KQha6LHruPkUmqpbTP9sOI2vckZMTJdJnGXzc37TfHcOZdFJRy3zudqw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "08882391-880b-473e-91ae-1a5737cde76f",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-9"
                        },
                        new
                        {
                            Id = "beec5833-451a-4368-9ea9-a97c39abd83c",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "367aa953-f9be-49c1-99f6-b12362849da5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-1020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-1020@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-10",
                            PasswordHash = "AQAAAAIAAYagAAAAEDjMkTyTP5KudIQCrPuOmj4i8yJPBkuUK6icX5uQPcFu4OrzQKTOMKaaH5HVqEqBSg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "329fe26b-cf66-4b97-8464-279f9b281d21",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-10"
                        },
                        new
                        {
                            Id = "0d1fc5f5-e9d5-4388-b416-5738bcc32b8e",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "4ddd8642-7cc2-4860-abc5-0f5d84068f9a",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1120@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-11",
                            PasswordHash = "AQAAAAIAAYagAAAAEPAkL7inPXw56Ze4rb4t2J4S3VU5sdEn3TScUHfCjdk8ng3NVyJqdu1Q4lvtdN6dDQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "17801a42-96cd-4fc0-9e4b-5c64078e62f1",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-11"
                        },
                        new
                        {
                            Id = "e03b40ff-5aaa-4e14-965e-13ff111dba28",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "e2562827-9107-46a1-b103-9d9d268101bd",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-1220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-1220@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-12",
                            PasswordHash = "AQAAAAIAAYagAAAAEK/hNdP8yFlCVnYK6Y9yqoox7t5VsiWtHT1Goyh/+NtDYXmZ/yfiPhTBeM32zl1kqg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "d8de1500-aa74-43e7-95f0-637cac51b375",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-12"
                        },
                        new
                        {
                            Id = "46d2ec69-1b80-4268-816d-91a9cd5c6d45",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "63a068f4-1bba-4256-964e-46961459a931",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-1320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-1320@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-13",
                            PasswordHash = "AQAAAAIAAYagAAAAEIhtbZmj057Q0IspHOZv+tWrT+SdFW5yXXi6AiEfELlwj85GUHhBPWXJUJizZbC9yA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "93fa638f-ec88-4d3b-878b-3e87da01caa8",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-13"
                        },
                        new
                        {
                            Id = "ffb887aa-9a30-4546-96b7-e1ee88ca531b",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "cd3f15f6-baa6-465d-95c0-c2bd26f0fafd",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-1420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-1420@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-14",
                            PasswordHash = "AQAAAAIAAYagAAAAEFWaaiY0/GGYnqskQYCKGhjSHl1upcVewbDIc0bUanFTr+FaOgQVpOl+NpCE/ILjwQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "0cf39dfe-90d0-42fd-a897-ab56cfaa874e",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-14"
                        },
                        new
                        {
                            Id = "af1133a3-3442-4fa3-8803-38676761dae2",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "db3ca98e-ea53-4277-9b3a-6e83bed7c385",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-1520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-1520@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-15",
                            PasswordHash = "AQAAAAIAAYagAAAAEJU0hIEslUI9TYbRMJLUSjf+AhAxWsOZz+IVshUB6OI9BNvqvzhLfIlrlDQKz6Opyg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "492dbccd-1ceb-4942-8218-788b510d9de5",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-15"
                        },
                        new
                        {
                            Id = "922646cd-85e6-4a66-ad60-b8ca7f529c95",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "75e0a619-afb4-4cff-ac54-6bf6297080e0",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-1620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-1620@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-16",
                            PasswordHash = "AQAAAAIAAYagAAAAELq6U5Rzr7GZH3Qfkm/te3XFMUKrL23NGITY2rfwgz2hxBziR4WRLgsY+ooL7QWmkA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "bd7f435a-3960-49a5-88f9-1ae75b7f119b",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-16"
                        },
                        new
                        {
                            Id = "63ad0649-553f-4056-9706-45469314585b",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "d493ab85-3293-46c1-a028-bda4b34ce62f",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-1720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-1720@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-17",
                            PasswordHash = "AQAAAAIAAYagAAAAEEuxrVHFexwNUmxgP3LAHPwlss94tqkx98foC3mr2RpAAk9MyTL9uudpeEsE7AxNKQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "690fedfd-f5d2-4236-8068-79445dd955ff",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-17"
                        },
                        new
                        {
                            Id = "0334e077-1844-4f18-ab57-a853f5e03533",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "9cf61533-7df6-4de2-a595-c95bc8478abc",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1820@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-18",
                            PasswordHash = "AQAAAAIAAYagAAAAENhoQvvlYy+1kTy929GnVhbL4tJRl+Awo7b7fyVGYpo2gzk8VfdccQPE8nk++IVNXw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "d6a64c25-5e99-4fd1-a068-d2dabba1979d",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-18"
                        },
                        new
                        {
                            Id = "cf90959d-9b41-4096-9043-6916e6020132",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "2c9e9da5-d42d-49f9-87fe-7c910839c592",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1920@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-19",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+gdbHsEa2sCsEiFx++c4U60O6YQ42Ykkjth/m7h1FhRNqQrdQCT84yg9y/WP0Akg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "b6455faf-4002-490f-8d37-cc70dd72d770",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-19"
                        },
                        new
                        {
                            Id = "497879a0-53c2-4d2a-8dcb-85cd97feda70",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "9d882081-0183-49f4-b6eb-96ad593dee43",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-2020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-2020@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-20",
                            PasswordHash = "AQAAAAIAAYagAAAAENYSLQYW4PjNfLNWJxd25OBqrN/fKlEXtA+VdgkrI34XVZDcnG/Chx77T7ON0vMfiQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "aa0496d6-f877-4da4-89af-d77b7f5da359",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-20"
                        },
                        new
                        {
                            Id = "b2867a00-80e0-4e01-91ee-e62a4c4fd57f",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "52e3baf6-824a-4869-85c5-259c06208b3a",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-2120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-2120@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-21",
                            PasswordHash = "AQAAAAIAAYagAAAAEH+QofXyg2YsxfzyvneBnICNk8eKAPElbcqcgWl/fz/RhuvIkvmZE7S2iTUOPsC6kQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "dd2423f5-de83-48af-9535-78671de920cb",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-21"
                        },
                        new
                        {
                            Id = "1b5fc552-7ea9-41f8-a79d-81a41a8ddabe",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "aadaf7f5-56b0-471b-98b1-22625f1b58fc",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2220@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-22",
                            PasswordHash = "AQAAAAIAAYagAAAAEFem7cIVlfAYOHj1Iao9kmXFEl3FB+GiysFP10oD3NLHmOfBF9x91xd9m2PjPWycKQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "11076068-39d6-4733-87ac-8375d1f969e6",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-22"
                        },
                        new
                        {
                            Id = "603ba261-67a4-4531-a01f-5b511f01ea87",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "7a945f89-4c02-4719-bb52-5fbb7f47cbcc",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-2320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-2320@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-23",
                            PasswordHash = "AQAAAAIAAYagAAAAEGc93aeIPIAq2gf87JyIAAixbr8s6w3FugHhSxphKGtTs1kwPnzVuGvU8fZXrC6hag==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "5cc1e42f-e54b-4f0e-a0fe-902352707eb1",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-23"
                        },
                        new
                        {
                            Id = "504c7528-d470-43e1-ae41-a2490c4bee68",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "7f14b07f-b8b0-474b-9d54-424534e5eea6",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-2420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-2420@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-24",
                            PasswordHash = "AQAAAAIAAYagAAAAEPE0o63ViUdUhEGQLFGyULD/E2MDy4RBz2Ju+rtjAriDh2jjnuhQF/COVKBbMzSgUA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "c343289b-96e5-4d0d-8e55-e47eaad68363",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-24"
                        },
                        new
                        {
                            Id = "7c834c1a-63c2-49d6-8950-16b112a99a88",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "630a69df-3a46-4f51-b555-1ac6bb49a2a7",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-2520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-2520@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-25",
                            PasswordHash = "AQAAAAIAAYagAAAAEJdaTNPil6DjlXfnX3pjbIIdZC52YpeeK8pH1nkojatJCkr0Q6JIyWRUxulqIdVBEg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "b30ded24-54c4-4c17-912d-88027d691d63",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-25"
                        },
                        new
                        {
                            Id = "29050854-c148-46a5-99ae-0a105386ea01",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "b92acf12-a355-4fbb-86b9-9b28a392c819",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-2620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-2620@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-26",
                            PasswordHash = "AQAAAAIAAYagAAAAEEo4FFBFCb1trSJirZqg5Q4D3iOa3/DH1G7E12fu0lJUdQFqk1LD4lpdOHecsnlTMQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "6647e04c-d0ba-483f-83c4-c570c2da9864",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-26"
                        },
                        new
                        {
                            Id = "d7814207-b301-4088-9d15-3020554c46b5",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "d4bf48f6-fbd5-460d-8f5f-780825e549f8",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-2720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-2720@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-27",
                            PasswordHash = "AQAAAAIAAYagAAAAEOdl2elNkcNVXQuc89E0hKuGwIR/bOU/YulxdK1n/hJoCVaNmC3dRsSAg+uy2QEpSQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "db70bec7-c943-4822-871a-58b326e5acf4",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-27"
                        },
                        new
                        {
                            Id = "91af8243-3c52-4469-95de-8c204f6d2587",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "77584270-4969-4333-809b-47416565ee33",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-2820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-2820@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-28",
                            PasswordHash = "AQAAAAIAAYagAAAAEJORdXqLUV2HU/e5bFc4sWAmTW4BAk01TMXBDA7f8ar39ECoQoR64IUhk0B9tIRzvg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "ababb8c5-0e9e-4795-86a3-12c880a24964",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-28"
                        },
                        new
                        {
                            Id = "0fb877f6-604c-4c1c-ab43-03c97a1dd596",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "9e7ccdb9-f580-4c4a-9fcc-ec0c6954adb5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2920@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-29",
                            PasswordHash = "AQAAAAIAAYagAAAAEJhkNxJ1Z1vbAARnErejn10U/2F6Qm6WkPMVSFyA9YKfWqba3L/kQYsIWCGmNm/C7g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            SecurityStamp = "008e6847-0825-43b3-b269-49249a4cd274",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-29"
                        },
                        new
                        {
                            Id = "2acde688-494b-4956-9182-5d1fed4dfaf3",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "5c74f3e4-c067-4903-bf0f-e3b1a22c4978",
                            Description = "I am the admin! Call me the Boss!!!",
                            Email = "VladBalkar20@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBALKAR20@MAIL.RU",
                            NormalizedUserName = "VLADBALKAR",
                            PasswordHash = "AQAAAAIAAYagAAAAEFuXKaUPapHDjgot+lJ3lgl0z1hs1oz3RppADP/5TEh2GbkJlyWp5aepKpNMd3zh2Q==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "7ca63ccf-40c1-4dad-8566-cf655ad0276f",
                            SecurityStamp = "81c2f5eb-8a6f-412e-9acb-1f6a96420eaf",
                            TwoFactorEnabled = false,
                            UserName = "VladBalkar"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1823615461,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "696d4813-0633-4d12-b9c2-d18c013c66ff"
                        },
                        new
                        {
                            Id = 103478178,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "696d4813-0633-4d12-b9c2-d18c013c66ff"
                        },
                        new
                        {
                            Id = 1594042342,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "696d4813-0633-4d12-b9c2-d18c013c66ff"
                        },
                        new
                        {
                            Id = 669358589,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "7dd506f9-90d1-442f-bc9b-9c38fef8a2b6"
                        },
                        new
                        {
                            Id = 140589574,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "7dd506f9-90d1-442f-bc9b-9c38fef8a2b6"
                        },
                        new
                        {
                            Id = 582404597,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "7dd506f9-90d1-442f-bc9b-9c38fef8a2b6"
                        },
                        new
                        {
                            Id = 1324986701,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "7dd506f9-90d1-442f-bc9b-9c38fef8a2b6"
                        },
                        new
                        {
                            Id = 1709967383,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "bdc4cbd4-6592-4700-b731-15d28f998f7d"
                        },
                        new
                        {
                            Id = 503428532,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "bdc4cbd4-6592-4700-b731-15d28f998f7d"
                        },
                        new
                        {
                            Id = 851572518,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "bdc4cbd4-6592-4700-b731-15d28f998f7d"
                        },
                        new
                        {
                            Id = 884436642,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "7232a042-1047-42fd-96ba-c72aed57e2ae"
                        },
                        new
                        {
                            Id = 216984146,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "7232a042-1047-42fd-96ba-c72aed57e2ae"
                        },
                        new
                        {
                            Id = 2008160269,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "40677c08-c27d-45ee-8c11-2887d7bc13b7"
                        },
                        new
                        {
                            Id = 786499965,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "40677c08-c27d-45ee-8c11-2887d7bc13b7"
                        },
                        new
                        {
                            Id = 443021833,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "40677c08-c27d-45ee-8c11-2887d7bc13b7"
                        },
                        new
                        {
                            Id = 1313409634,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "18523064-eb41-4a03-9400-70ff589137de"
                        },
                        new
                        {
                            Id = 1982031131,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "18523064-eb41-4a03-9400-70ff589137de"
                        },
                        new
                        {
                            Id = 1142017555,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "3e43fb1f-0f56-4495-8d4c-25e2afe44b53"
                        },
                        new
                        {
                            Id = 2080081263,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "1281817d-a915-4a2b-823f-54f566386052"
                        },
                        new
                        {
                            Id = 28280268,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "1281817d-a915-4a2b-823f-54f566386052"
                        },
                        new
                        {
                            Id = 1983575816,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "1281817d-a915-4a2b-823f-54f566386052"
                        },
                        new
                        {
                            Id = 791501061,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "1281817d-a915-4a2b-823f-54f566386052"
                        },
                        new
                        {
                            Id = 508393440,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "1281817d-a915-4a2b-823f-54f566386052"
                        },
                        new
                        {
                            Id = 684380882,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "1281817d-a915-4a2b-823f-54f566386052"
                        },
                        new
                        {
                            Id = 136726156,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "83e22dfe-e470-44aa-9502-6925be3633f2"
                        },
                        new
                        {
                            Id = 924376833,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "83e22dfe-e470-44aa-9502-6925be3633f2"
                        },
                        new
                        {
                            Id = 1005861021,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "83e22dfe-e470-44aa-9502-6925be3633f2"
                        },
                        new
                        {
                            Id = 1797463786,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "3ed8231c-9dca-4371-b091-a40ab198492d"
                        },
                        new
                        {
                            Id = 2093930736,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c"
                        },
                        new
                        {
                            Id = 1565671680,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c"
                        },
                        new
                        {
                            Id = 1254691601,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c"
                        },
                        new
                        {
                            Id = 1493193349,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c"
                        },
                        new
                        {
                            Id = 1900669603,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c"
                        },
                        new
                        {
                            Id = 1745679526,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c"
                        },
                        new
                        {
                            Id = 435195674,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "0d1fc5f5-e9d5-4388-b416-5738bcc32b8e"
                        },
                        new
                        {
                            Id = 1456073085,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "0d1fc5f5-e9d5-4388-b416-5738bcc32b8e"
                        },
                        new
                        {
                            Id = 695260558,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "0d1fc5f5-e9d5-4388-b416-5738bcc32b8e"
                        },
                        new
                        {
                            Id = 1137717189,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "0d1fc5f5-e9d5-4388-b416-5738bcc32b8e"
                        },
                        new
                        {
                            Id = 474645019,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "e03b40ff-5aaa-4e14-965e-13ff111dba28"
                        },
                        new
                        {
                            Id = 1929172809,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "e03b40ff-5aaa-4e14-965e-13ff111dba28"
                        },
                        new
                        {
                            Id = 753208947,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "e03b40ff-5aaa-4e14-965e-13ff111dba28"
                        },
                        new
                        {
                            Id = 832144667,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "46d2ec69-1b80-4268-816d-91a9cd5c6d45"
                        },
                        new
                        {
                            Id = 1547917724,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "46d2ec69-1b80-4268-816d-91a9cd5c6d45"
                        },
                        new
                        {
                            Id = 1270070260,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b"
                        },
                        new
                        {
                            Id = 1557487273,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b"
                        },
                        new
                        {
                            Id = 157667743,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b"
                        },
                        new
                        {
                            Id = 790956864,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b"
                        },
                        new
                        {
                            Id = 1241752126,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b"
                        },
                        new
                        {
                            Id = 1667988718,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b"
                        },
                        new
                        {
                            Id = 1779907796,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "af1133a3-3442-4fa3-8803-38676761dae2"
                        },
                        new
                        {
                            Id = 190173174,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "af1133a3-3442-4fa3-8803-38676761dae2"
                        },
                        new
                        {
                            Id = 1570932909,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "af1133a3-3442-4fa3-8803-38676761dae2"
                        },
                        new
                        {
                            Id = 1196765189,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "922646cd-85e6-4a66-ad60-b8ca7f529c95"
                        },
                        new
                        {
                            Id = 1360857629,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "922646cd-85e6-4a66-ad60-b8ca7f529c95"
                        },
                        new
                        {
                            Id = 1367896135,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "922646cd-85e6-4a66-ad60-b8ca7f529c95"
                        },
                        new
                        {
                            Id = 524400016,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "922646cd-85e6-4a66-ad60-b8ca7f529c95"
                        },
                        new
                        {
                            Id = 235441390,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "922646cd-85e6-4a66-ad60-b8ca7f529c95"
                        },
                        new
                        {
                            Id = 73342606,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "63ad0649-553f-4056-9706-45469314585b"
                        },
                        new
                        {
                            Id = 1022844598,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "63ad0649-553f-4056-9706-45469314585b"
                        },
                        new
                        {
                            Id = 603739166,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "63ad0649-553f-4056-9706-45469314585b"
                        },
                        new
                        {
                            Id = 1371681697,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "63ad0649-553f-4056-9706-45469314585b"
                        },
                        new
                        {
                            Id = 1857690244,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "63ad0649-553f-4056-9706-45469314585b"
                        },
                        new
                        {
                            Id = 906022073,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "63ad0649-553f-4056-9706-45469314585b"
                        },
                        new
                        {
                            Id = 263368951,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533"
                        },
                        new
                        {
                            Id = 1455843256,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533"
                        },
                        new
                        {
                            Id = 953299337,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533"
                        },
                        new
                        {
                            Id = 1851930881,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533"
                        },
                        new
                        {
                            Id = 1810752983,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533"
                        },
                        new
                        {
                            Id = 2128971394,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533"
                        },
                        new
                        {
                            Id = 1120622573,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "cf90959d-9b41-4096-9043-6916e6020132"
                        },
                        new
                        {
                            Id = 624838868,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "cf90959d-9b41-4096-9043-6916e6020132"
                        },
                        new
                        {
                            Id = 36686087,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "cf90959d-9b41-4096-9043-6916e6020132"
                        },
                        new
                        {
                            Id = 1525646343,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "497879a0-53c2-4d2a-8dcb-85cd97feda70"
                        },
                        new
                        {
                            Id = 1529357621,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "497879a0-53c2-4d2a-8dcb-85cd97feda70"
                        },
                        new
                        {
                            Id = 2086782098,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "497879a0-53c2-4d2a-8dcb-85cd97feda70"
                        },
                        new
                        {
                            Id = 492421820,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "b2867a00-80e0-4e01-91ee-e62a4c4fd57f"
                        },
                        new
                        {
                            Id = 1597596680,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "1b5fc552-7ea9-41f8-a79d-81a41a8ddabe"
                        },
                        new
                        {
                            Id = 897621355,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "603ba261-67a4-4531-a01f-5b511f01ea87"
                        },
                        new
                        {
                            Id = 819325692,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "603ba261-67a4-4531-a01f-5b511f01ea87"
                        },
                        new
                        {
                            Id = 1191604108,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "603ba261-67a4-4531-a01f-5b511f01ea87"
                        },
                        new
                        {
                            Id = 233677579,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68"
                        },
                        new
                        {
                            Id = 48428737,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68"
                        },
                        new
                        {
                            Id = 1850413661,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68"
                        },
                        new
                        {
                            Id = 1988306730,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68"
                        },
                        new
                        {
                            Id = 1655760898,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68"
                        },
                        new
                        {
                            Id = 447914785,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68"
                        },
                        new
                        {
                            Id = 726836865,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88"
                        },
                        new
                        {
                            Id = 236843860,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88"
                        },
                        new
                        {
                            Id = 1526090571,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88"
                        },
                        new
                        {
                            Id = 1955055517,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88"
                        },
                        new
                        {
                            Id = 796010034,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88"
                        },
                        new
                        {
                            Id = 1798489050,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88"
                        },
                        new
                        {
                            Id = 1363474163,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "29050854-c148-46a5-99ae-0a105386ea01"
                        },
                        new
                        {
                            Id = 2061595474,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "29050854-c148-46a5-99ae-0a105386ea01"
                        },
                        new
                        {
                            Id = 1748867176,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "29050854-c148-46a5-99ae-0a105386ea01"
                        },
                        new
                        {
                            Id = 1669245676,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "d7814207-b301-4088-9d15-3020554c46b5"
                        },
                        new
                        {
                            Id = 1558509429,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "d7814207-b301-4088-9d15-3020554c46b5"
                        },
                        new
                        {
                            Id = 1335075547,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "d7814207-b301-4088-9d15-3020554c46b5"
                        },
                        new
                        {
                            Id = 1432732510,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "d7814207-b301-4088-9d15-3020554c46b5"
                        },
                        new
                        {
                            Id = 1811878617,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "91af8243-3c52-4469-95de-8c204f6d2587"
                        },
                        new
                        {
                            Id = 54145799,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "91af8243-3c52-4469-95de-8c204f6d2587"
                        },
                        new
                        {
                            Id = 1297880112,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "0fb877f6-604c-4c1c-ab43-03c97a1dd596"
                        },
                        new
                        {
                            Id = 1072259701,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "0fb877f6-604c-4c1c-ab43-03c97a1dd596"
                        },
                        new
                        {
                            Id = 985042060,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "0fb877f6-604c-4c1c-ab43-03c97a1dd596"
                        },
                        new
                        {
                            Id = 1979850641,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "0fb877f6-604c-4c1c-ab43-03c97a1dd596"
                        },
                        new
                        {
                            Id = 1105441914,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "0fb877f6-604c-4c1c-ab43-03c97a1dd596"
                        },
                        new
                        {
                            Id = 1187437816,
                            ClaimType = "BossClaim",
                            ClaimValue = "BossClaim",
                            UserId = "2acde688-494b-4956-9182-5d1fed4dfaf3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "696d4813-0633-4d12-b9c2-d18c013c66ff",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "7dd506f9-90d1-442f-bc9b-9c38fef8a2b6",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "bdc4cbd4-6592-4700-b731-15d28f998f7d",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "7232a042-1047-42fd-96ba-c72aed57e2ae",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "40677c08-c27d-45ee-8c11-2887d7bc13b7",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "18523064-eb41-4a03-9400-70ff589137de",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "3e43fb1f-0f56-4495-8d4c-25e2afe44b53",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "1281817d-a915-4a2b-823f-54f566386052",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "83e22dfe-e470-44aa-9502-6925be3633f2",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "3ed8231c-9dca-4371-b091-a40ab198492d",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "beec5833-451a-4368-9ea9-a97c39abd83c",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "0d1fc5f5-e9d5-4388-b416-5738bcc32b8e",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "e03b40ff-5aaa-4e14-965e-13ff111dba28",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "46d2ec69-1b80-4268-816d-91a9cd5c6d45",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "ffb887aa-9a30-4546-96b7-e1ee88ca531b",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "af1133a3-3442-4fa3-8803-38676761dae2",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "922646cd-85e6-4a66-ad60-b8ca7f529c95",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "63ad0649-553f-4056-9706-45469314585b",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "0334e077-1844-4f18-ab57-a853f5e03533",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "cf90959d-9b41-4096-9043-6916e6020132",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "497879a0-53c2-4d2a-8dcb-85cd97feda70",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "b2867a00-80e0-4e01-91ee-e62a4c4fd57f",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "1b5fc552-7ea9-41f8-a79d-81a41a8ddabe",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "603ba261-67a4-4531-a01f-5b511f01ea87",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "504c7528-d470-43e1-ae41-a2490c4bee68",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "7c834c1a-63c2-49d6-8950-16b112a99a88",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "29050854-c148-46a5-99ae-0a105386ea01",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "d7814207-b301-4088-9d15-3020554c46b5",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "91af8243-3c52-4469-95de-8c204f6d2587",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "0fb877f6-604c-4c1c-ab43-03c97a1dd596",
                            RoleId = "891f612b-164b-4c9c-b8a9-d76f59ad5389"
                        },
                        new
                        {
                            UserId = "2acde688-494b-4956-9182-5d1fed4dfaf3",
                            RoleId = "7ca63ccf-40c1-4dad-8566-cf655ad0276f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("UserEntityId");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<string>");

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "7ca63ccf-40c1-4dad-8566-cf655ad0276f",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "6ec98da5-faaf-4e8f-971a-7036e011a2b2",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        },
                        new
                        {
                            Id = "891f612b-164b-4c9c-b8a9-d76f59ad5389",
                            Name = "Pooper",
                            NormalizedName = "POOPER"
                        },
                        new
                        {
                            Id = "0ba08ca6-f67a-4193-a58c-2f9174b5a320",
                            Name = "Reviwer",
                            NormalizedName = "REVIWER"
                        },
                        new
                        {
                            Id = "94a29c58-e3e1-4677-a2ae-7ae380198e23",
                            Name = "Maker",
                            NormalizedName = "MAKER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Auh.Entities.UserEntity", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
