// <auto-generated />
using System;
using Data.IdentityDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityDb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240229143138_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Auh.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AmountOfPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b3023d3d-0a25-43ac-ba10-3815be222227",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "aab87d16-a9bb-4d75-979d-ef7bebc6a914",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-020@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-0",
                            PasswordHash = "AQAAAAIAAYagAAAAELbhvlfiafcTOIVJlIdJoe6WLWPX/Cr1vySS7ULwIduQwT//dFjbqpniULn86Yecjw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "d2e15602-19d7-48ad-9789-b24ee89a29d7",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-0"
                        },
                        new
                        {
                            Id = "775134f4-446d-4393-a01d-8e52bd08ff78",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "7904308f-a49f-413e-8027-fd42904c7df0",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-120@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-1",
                            PasswordHash = "AQAAAAIAAYagAAAAEB0aV205JlCYXfEodx+DCXYlsBPgxuVQUpy04BdPQ2YuYD28PiGW5GTf+I+rGh4g2Q==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "b4182e9d-770b-4b24-b134-fbf9f563064e",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-1"
                        },
                        new
                        {
                            Id = "906f6fc5-68ee-431b-be2e-2545682da6bd",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "8c5064f0-6dce-423f-a73e-f6fcb0fd5cf8",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-220@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-2",
                            PasswordHash = "AQAAAAIAAYagAAAAEKi63qS8xVFquS+MPaEtciG0IkPQYHK/CS4ptzMTWJ67oIaIHpq7tchiPrAJpGt6ZA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "7d2e5590-23bc-4878-aa02-e3bf8a3d7ed4",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-2"
                        },
                        new
                        {
                            Id = "c9af9594-c82f-4069-84eb-4d3793d987b9",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "d2a50c9a-efdb-460d-9c16-6db2b8a02725",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-320@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-3",
                            PasswordHash = "AQAAAAIAAYagAAAAEMN53fZD+jSaF+wvkcgk+yKKCh+B+5Nc2BzzFGz3+HUYWMTfChXxvMcMOA7xiopfwA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "94d0d49e-35af-4002-84b5-d5b50fc919f1",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-3"
                        },
                        new
                        {
                            Id = "d23163db-be3e-4fd5-a5da-2f72c768c05a",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "4c007207-8ad5-4776-8275-49b195a73e53",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-420@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-4",
                            PasswordHash = "AQAAAAIAAYagAAAAEOCyeSbGD83XYfYmHxU2+Y6fJ+OsVGnqhSJv3n+U5Q9JecqTWT8uW15EjZEr7vTSFw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "3e912ec5-263b-4994-b233-40783930ac85",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-4"
                        },
                        new
                        {
                            Id = "dba21b20-7551-488a-bb08-40f034e0b475",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "3aa8c73a-6479-4d4f-89d0-48c75e4b6642",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-520@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-5",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4S5zEVQvfIwuMNRH6mRdfBH/kpTZugtBN2FUQz+OkezyWkmsdwn5WkS2n+GDakHg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "f50778a5-4300-4df3-8eac-90700254470c",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-5"
                        },
                        new
                        {
                            Id = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "bb735063-0a6d-4571-903f-614d6125ac84",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-620@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-6",
                            PasswordHash = "AQAAAAIAAYagAAAAEFlA1ZhJV/sx1RXgn6mYmpiZlD0QhJnTe1F/IgBk4jwBBsSf7q9ugUQTswxPxPb9eQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "1800b893-1b12-4aeb-8c94-7f470d34e6a6",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-6"
                        },
                        new
                        {
                            Id = "67b764c8-35e7-462a-95e6-b39f2291c4fe",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "0db5944b-4d44-42d0-ad33-8da94c1b9aff",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-720@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-7",
                            PasswordHash = "AQAAAAIAAYagAAAAEGyHgBQOlq2THuSEe99uaRBuKyqxUe3nuoan+1SDqbxReII2x/gNQeQE0Ew/zdtS2w==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "08df3d38-e66f-46fc-92b2-7f47b869fb69",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-7"
                        },
                        new
                        {
                            Id = "40dee089-43c6-4781-b39c-b320375a0f10",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "582c92da-d1b0-4c4b-ac0e-8c8ee70a71e4",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-820@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-8",
                            PasswordHash = "AQAAAAIAAYagAAAAEA8kb9OXME/U7fdLPPhIdD4ImcxsYIsIe5Kyhk9KEy/ohylUNMrjPlVezkaNmEHDeA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "cb045dbe-1069-444f-aee8-021e12473488",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-8"
                        },
                        new
                        {
                            Id = "97d4c05f-c0a0-475a-9ba5-7d027d193c60",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "40865ac6-566a-44a6-a70e-38451e90f1c3",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-920@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-9",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0Xf9n8q8GX4g8k+FhipxCiizt/BFQ9zvqCOxhWdB1KAfslFXwMkX2AXPsPQ9dAWg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "2fc6960b-cc3a-419c-9b30-4440d2947dc5",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-9"
                        },
                        new
                        {
                            Id = "c1713cd1-099d-4de3-bd55-11192ec724ad",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "67e0672c-fd8e-4fb1-9250-2fc0f6d2217b",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1020@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-10",
                            PasswordHash = "AQAAAAIAAYagAAAAEGHkSJo/0Ej2xLBd4RUkRQzOeT9MFw76eiAzd/UmtpBhk4IH/WD5+UWzcczsppx/uQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "6a7c48e8-e16c-49d8-aa74-77a4e517082d",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-10"
                        },
                        new
                        {
                            Id = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "61ad0ef0-34fa-48a5-b8fb-4d4312ec1a38",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1120@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-11",
                            PasswordHash = "AQAAAAIAAYagAAAAECEcMyIhoGwLI/6HW4ImyBmvkko++Nw+eUXcmThS5TuHBple6OTA7wmYPEewtGwL4g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "dfd043f1-a08d-4cbb-8620-df7a78f8fca8",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-11"
                        },
                        new
                        {
                            Id = "8021b9a7-dca8-4940-b587-3fb85064c8a1",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "88a8ad62-3a21-49bc-a5aa-977ad7673f93",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1220@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-12",
                            PasswordHash = "AQAAAAIAAYagAAAAEI7EYo/0ZTRr6ecT7cTsRfcdDAl8MWMBNUanc/bV0gf7fmaTtmVIswpf20EZvoYAzQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "addced64-0274-49de-8f90-b4dd75e1eb2c",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-12"
                        },
                        new
                        {
                            Id = "aef95f03-48d8-4397-b0c3-3b5b09f8375f",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "d51587f7-9c67-4167-ac24-c04b9d0a2636",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-1320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-1320@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-13",
                            PasswordHash = "AQAAAAIAAYagAAAAEAOitqXH8QzM4EmwNrVU4gZ+tyDqKVdQT/uTu5miNSkpovukID8TWy2Ls9dEY0thlg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "4cab2cb5-0148-4037-8552-2ffae42f228e",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-13"
                        },
                        new
                        {
                            Id = "8e39a8f9-830a-4cfc-bbc1-462b84c85b71",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "2cb0863b-c0a3-481f-bbc0-62ab0b9daa4f",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-1420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-1420@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-14",
                            PasswordHash = "AQAAAAIAAYagAAAAEP3BXTcBiyTdUdFOdj6JPhKNZOXnM/PLctPgh83W7/bo+aJdI2vcYp5IGSHTymlt6g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "a67433c3-6dee-444c-a3f4-f52c88dcb306",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-14"
                        },
                        new
                        {
                            Id = "569e6ec9-987b-484d-bfde-b393fed2b933",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "36291a61-2485-4ec2-bd0f-fdf1a866a038",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1520@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-15",
                            PasswordHash = "AQAAAAIAAYagAAAAEGTenJ/Omy0cEhqXLcf4CpKVXxVRhiR7HVSUL29vCdYvHrqwOOza2OgDZQ53BqSOFQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "1bf538b1-8f95-4c54-993d-b1e9c319e4c4",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-15"
                        },
                        new
                        {
                            Id = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "70a652e7-f9f3-448f-87e2-f5c2f690d810",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1620@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-16",
                            PasswordHash = "AQAAAAIAAYagAAAAEDIB7EMNQ5+Dc5GnlppuIuWMZM+vSNWolGb6vTafwGlZDMejyLmpDEUZgcEGxszGuA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "1572cc96-cc31-4811-ad03-e9bcdfa8fc21",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-16"
                        },
                        new
                        {
                            Id = "149a9b6c-a589-4a22-82f0-e655a84210ee",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "7fcb1222-411c-4621-a4a2-6b857267b671",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1720@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-17",
                            PasswordHash = "AQAAAAIAAYagAAAAEE9JcoNt3YY0hAwMBdTlc+mJiM/DDnLgzDqVUhgfj/rxJLuTxfxSjm2JJT8a5YOODQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "cc9b6f19-e394-48ef-aad6-0170ef2e0604",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-17"
                        },
                        new
                        {
                            Id = "71827788-34d5-458b-b030-99c0fa21dd42",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "b97efea8-acbe-4436-8931-20e2aa8d8b38",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1820@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-18",
                            PasswordHash = "AQAAAAIAAYagAAAAEDmC55W2LE+6dcVV/cWv2C6ep1ECQzQnWt0iZXo/hRIRTX34AijfZMSP2YLpGPHLCQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "83397ea2-1a79-4d59-acaf-9bbb5dc7772a",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-18"
                        },
                        new
                        {
                            Id = "52c7c03e-6b9c-43c8-93cd-6d0c38af2520",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "a0d7c3bc-9f9a-43be-a381-b486f1b33c95",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1920@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-19",
                            PasswordHash = "AQAAAAIAAYagAAAAEOLVWXnpVcH217ikfFDLqpbxNyvzQuM0Z48BmQmU4OTC8jX6kByA8x4c1AQsgJXZGg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "231ebf6e-56f3-4ac0-908b-8f0c26ae58b9",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-19"
                        },
                        new
                        {
                            Id = "2506ad74-1604-4a0e-bfff-d434b16344ae",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "c36508de-2286-415c-ad4d-0f58e1274bd6",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-2020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-2020@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-20",
                            PasswordHash = "AQAAAAIAAYagAAAAEPS5Rlw5y6W4rHgNoPBCl5h+VUdA6dZMQ4uZFK6jTt5WtRLli5cpDQ9+hhZhcwFlsw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "fa51c59c-82f2-428a-b9cf-09dbf11c65d1",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-20"
                        },
                        new
                        {
                            Id = "ed1e6df8-af68-44cc-80ff-e32937583545",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "3d267db2-1267-4515-97dd-b048eb017f73",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2120@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-21",
                            PasswordHash = "AQAAAAIAAYagAAAAECn+M2iaVSWEZqKiHauRPxU3kE153400HFXbEi8XLxe638y5Fi6Y/e4rkhkvpOlgKQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "3cb8913c-ab60-4fde-bb0e-9d072185d30f",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-21"
                        },
                        new
                        {
                            Id = "0034b642-85f5-4c06-bb37-a500e288c187",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "b8909bce-52c5-4c61-9c16-ec798a5b2bac",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-2220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-2220@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-22",
                            PasswordHash = "AQAAAAIAAYagAAAAEH2XGLtp3wLYacxSkcVsF6lQKcW0OzmaRdhJ97kKsu4KS/tegpJjLhXRgdYXL+cilQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "f1ddbd45-8fe4-4845-9504-9d6f4bc5225b",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-22"
                        },
                        new
                        {
                            Id = "1f809152-0401-4ab0-b80d-e61d046e7e30",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "1dde0fe7-c656-41e4-821c-d54217d29cbb",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-2320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-2320@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-23",
                            PasswordHash = "AQAAAAIAAYagAAAAEC85P8yjKup6ScJoNXTUITTE5yM6L+U3tSZ6S1YMPu93uFAW+FLtYFKVnfc15DZAIw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "8be09681-aabc-4518-8ca5-5120aad84f1d",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-23"
                        },
                        new
                        {
                            Id = "bd552e5c-2adb-4974-aecc-43bfaf14fed9",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "209c6bac-4a04-4725-9632-12eed76f1c3b",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-2420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-2420@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-24",
                            PasswordHash = "AQAAAAIAAYagAAAAEDbvcLnQ+Ua4+5z899jgUecHTK9muhb6MpGXzeo8c0Ys6azpcQSAf7v1SrY7fjk+Hg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "34e9e35d-6c51-4b9c-9711-7b6574c557a4",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-24"
                        },
                        new
                        {
                            Id = "05d4176e-5516-4263-9561-750e6d07a75b",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "31a37648-9f76-42c8-92eb-76bac3248538",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2520@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-25",
                            PasswordHash = "AQAAAAIAAYagAAAAEHjUFWE561vV4liYt+Fh7s927hecylvtCASJPSKyjCgQR+WEdD67cm83mAaEcCKFyg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "36aaf59e-de76-4bf6-8b86-9838a25f3150",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-25"
                        },
                        new
                        {
                            Id = "7265999d-da9d-461c-a372-a1090a8a62ec",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "fabe3f08-65cc-4a30-8e43-74aa0a5b1ed8",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2620@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-26",
                            PasswordHash = "AQAAAAIAAYagAAAAEEfe/LYagVty/ynbrGy80dJ8w3b9RxQYMjdfpUB6JH2oLHogdT7uElQMnPxA7C1ACQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "a759e3da-591b-4a26-8d7f-b28f9f5d1591",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-26"
                        },
                        new
                        {
                            Id = "b44a894a-7a09-4543-9f02-cbcfd40cbb8d",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "970253c9-8d2c-4c43-8877-a3bede038ae9",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-2720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-2720@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-27",
                            PasswordHash = "AQAAAAIAAYagAAAAEDr8PcaEFVoEpeB/Lc1y3E1BR3o6IddC+fbioFSTMKqfTfasyr59b9UIlI/I1nwQaA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "c5ae7eea-d2ad-462d-a0eb-c942be25cbf4",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-27"
                        },
                        new
                        {
                            Id = "8de033fe-d7c2-4375-9e49-d7387fe86153",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "f8c07008-e8ed-4085-8aec-5d8193996bed",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2820@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-28",
                            PasswordHash = "AQAAAAIAAYagAAAAEKTg/EfkwFwUmNUq5WnOLJrcZz/atfuxGCJDk2QVutEZkZ3u47BIDkZ2YMf2RQB0ww==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "cd2ab6e5-5dc5-4cb7-9f25-710f89f866d7",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-28"
                        },
                        new
                        {
                            Id = "2ae52980-9c9e-4391-adf6-0390a3f82084",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "1abd7542-11cf-4eb8-8dda-7a70e38cf89b",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-2920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-2920@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-29",
                            PasswordHash = "AQAAAAIAAYagAAAAEM1te70waCZOzjGYmkA4SdHku3Sl0F6699Lxm9NIZehLdJ5leODMwaCqHogbCMBZ1w==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            SecurityStamp = "f41258f1-308b-4f4e-ac39-088014563d6e",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-29"
                        },
                        new
                        {
                            Id = "eda12e6b-c0da-4b5c-b5df-accdc0d91847",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "d69e64c0-a01b-4de4-aeb2-0d072e793dc3",
                            Description = "I am the admin! Call me the Boss!!!",
                            Email = "VladBalkar20@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBALKAR20@MAIL.RU",
                            NormalizedUserName = "VLADBALKAR",
                            PasswordHash = "AQAAAAIAAYagAAAAEMxshkAdnsDvEEhC1Iz7mQRrnRNm9V1Pgx6l7AoEMGElXngwuOHGFP7iKcQew16X4Q==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "f6ed4a0d-9d62-43dd-8b22-004a142bc227",
                            SecurityStamp = "fd8b6237-b249-457d-aa1e-1b361e7c671e",
                            TwoFactorEnabled = false,
                            UserName = "VladBalkar"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 969461130,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "b3023d3d-0a25-43ac-ba10-3815be222227"
                        },
                        new
                        {
                            Id = 1267591420,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "b3023d3d-0a25-43ac-ba10-3815be222227"
                        },
                        new
                        {
                            Id = 1135499982,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "b3023d3d-0a25-43ac-ba10-3815be222227"
                        },
                        new
                        {
                            Id = 1346341151,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "b3023d3d-0a25-43ac-ba10-3815be222227"
                        },
                        new
                        {
                            Id = 1672618307,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78"
                        },
                        new
                        {
                            Id = 656095921,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78"
                        },
                        new
                        {
                            Id = 87921071,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78"
                        },
                        new
                        {
                            Id = 177452456,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78"
                        },
                        new
                        {
                            Id = 1382469265,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78"
                        },
                        new
                        {
                            Id = 2099268837,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78"
                        },
                        new
                        {
                            Id = 74115542,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "906f6fc5-68ee-431b-be2e-2545682da6bd"
                        },
                        new
                        {
                            Id = 1029139120,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "906f6fc5-68ee-431b-be2e-2545682da6bd"
                        },
                        new
                        {
                            Id = 1381567465,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "906f6fc5-68ee-431b-be2e-2545682da6bd"
                        },
                        new
                        {
                            Id = 1695967758,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "906f6fc5-68ee-431b-be2e-2545682da6bd"
                        },
                        new
                        {
                            Id = 398947107,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "c9af9594-c82f-4069-84eb-4d3793d987b9"
                        },
                        new
                        {
                            Id = 1664487711,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "c9af9594-c82f-4069-84eb-4d3793d987b9"
                        },
                        new
                        {
                            Id = 1884352274,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "d23163db-be3e-4fd5-a5da-2f72c768c05a"
                        },
                        new
                        {
                            Id = 734446896,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "d23163db-be3e-4fd5-a5da-2f72c768c05a"
                        },
                        new
                        {
                            Id = 931760445,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "d23163db-be3e-4fd5-a5da-2f72c768c05a"
                        },
                        new
                        {
                            Id = 1796228221,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "d23163db-be3e-4fd5-a5da-2f72c768c05a"
                        },
                        new
                        {
                            Id = 387021760,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "dba21b20-7551-488a-bb08-40f034e0b475"
                        },
                        new
                        {
                            Id = 1685028985,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "dba21b20-7551-488a-bb08-40f034e0b475"
                        },
                        new
                        {
                            Id = 2011242017,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "dba21b20-7551-488a-bb08-40f034e0b475"
                        },
                        new
                        {
                            Id = 509122057,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "dba21b20-7551-488a-bb08-40f034e0b475"
                        },
                        new
                        {
                            Id = 1854720387,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "dba21b20-7551-488a-bb08-40f034e0b475"
                        },
                        new
                        {
                            Id = 1543335612,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a"
                        },
                        new
                        {
                            Id = 723473254,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a"
                        },
                        new
                        {
                            Id = 1707261684,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a"
                        },
                        new
                        {
                            Id = 1494175272,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a"
                        },
                        new
                        {
                            Id = 831056663,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a"
                        },
                        new
                        {
                            Id = 1623499305,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a"
                        },
                        new
                        {
                            Id = 836720500,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "67b764c8-35e7-462a-95e6-b39f2291c4fe"
                        },
                        new
                        {
                            Id = 1074980351,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "67b764c8-35e7-462a-95e6-b39f2291c4fe"
                        },
                        new
                        {
                            Id = 297144103,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "67b764c8-35e7-462a-95e6-b39f2291c4fe"
                        },
                        new
                        {
                            Id = 1584059505,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "67b764c8-35e7-462a-95e6-b39f2291c4fe"
                        },
                        new
                        {
                            Id = 324593259,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "67b764c8-35e7-462a-95e6-b39f2291c4fe"
                        },
                        new
                        {
                            Id = 719022104,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10"
                        },
                        new
                        {
                            Id = 408382374,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10"
                        },
                        new
                        {
                            Id = 1483670485,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10"
                        },
                        new
                        {
                            Id = 1985990734,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10"
                        },
                        new
                        {
                            Id = 2146327657,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10"
                        },
                        new
                        {
                            Id = 603514995,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10"
                        },
                        new
                        {
                            Id = 156896491,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "97d4c05f-c0a0-475a-9ba5-7d027d193c60"
                        },
                        new
                        {
                            Id = 1092087515,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "97d4c05f-c0a0-475a-9ba5-7d027d193c60"
                        },
                        new
                        {
                            Id = 118938034,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "c1713cd1-099d-4de3-bd55-11192ec724ad"
                        },
                        new
                        {
                            Id = 627245840,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "c1713cd1-099d-4de3-bd55-11192ec724ad"
                        },
                        new
                        {
                            Id = 785581740,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc"
                        },
                        new
                        {
                            Id = 648276513,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc"
                        },
                        new
                        {
                            Id = 346700899,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc"
                        },
                        new
                        {
                            Id = 1419443854,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc"
                        },
                        new
                        {
                            Id = 971969300,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc"
                        },
                        new
                        {
                            Id = 94213098,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc"
                        },
                        new
                        {
                            Id = 1924669843,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "8021b9a7-dca8-4940-b587-3fb85064c8a1"
                        },
                        new
                        {
                            Id = 973165427,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "8021b9a7-dca8-4940-b587-3fb85064c8a1"
                        },
                        new
                        {
                            Id = 80319825,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "aef95f03-48d8-4397-b0c3-3b5b09f8375f"
                        },
                        new
                        {
                            Id = 1556886131,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "aef95f03-48d8-4397-b0c3-3b5b09f8375f"
                        },
                        new
                        {
                            Id = 1488795376,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "aef95f03-48d8-4397-b0c3-3b5b09f8375f"
                        },
                        new
                        {
                            Id = 2025765925,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "aef95f03-48d8-4397-b0c3-3b5b09f8375f"
                        },
                        new
                        {
                            Id = 926531527,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "8e39a8f9-830a-4cfc-bbc1-462b84c85b71"
                        },
                        new
                        {
                            Id = 263197977,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "8e39a8f9-830a-4cfc-bbc1-462b84c85b71"
                        },
                        new
                        {
                            Id = 1604088658,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "8e39a8f9-830a-4cfc-bbc1-462b84c85b71"
                        },
                        new
                        {
                            Id = 1258981171,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "569e6ec9-987b-484d-bfde-b393fed2b933"
                        },
                        new
                        {
                            Id = 1832508832,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "569e6ec9-987b-484d-bfde-b393fed2b933"
                        },
                        new
                        {
                            Id = 186461090,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "569e6ec9-987b-484d-bfde-b393fed2b933"
                        },
                        new
                        {
                            Id = 1757094260,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2"
                        },
                        new
                        {
                            Id = 1440606044,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2"
                        },
                        new
                        {
                            Id = 1802908134,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2"
                        },
                        new
                        {
                            Id = 230328325,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2"
                        },
                        new
                        {
                            Id = 933042901,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2"
                        },
                        new
                        {
                            Id = 1113314316,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2"
                        },
                        new
                        {
                            Id = 1904438428,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "149a9b6c-a589-4a22-82f0-e655a84210ee"
                        },
                        new
                        {
                            Id = 1660809167,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "149a9b6c-a589-4a22-82f0-e655a84210ee"
                        },
                        new
                        {
                            Id = 1607538593,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "149a9b6c-a589-4a22-82f0-e655a84210ee"
                        },
                        new
                        {
                            Id = 737894017,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "149a9b6c-a589-4a22-82f0-e655a84210ee"
                        },
                        new
                        {
                            Id = 1094355230,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "149a9b6c-a589-4a22-82f0-e655a84210ee"
                        },
                        new
                        {
                            Id = 263686423,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42"
                        },
                        new
                        {
                            Id = 2113021204,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42"
                        },
                        new
                        {
                            Id = 1700253994,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42"
                        },
                        new
                        {
                            Id = 934105501,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42"
                        },
                        new
                        {
                            Id = 324913620,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42"
                        },
                        new
                        {
                            Id = 360875772,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42"
                        },
                        new
                        {
                            Id = 1108121292,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "52c7c03e-6b9c-43c8-93cd-6d0c38af2520"
                        },
                        new
                        {
                            Id = 740841528,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "52c7c03e-6b9c-43c8-93cd-6d0c38af2520"
                        },
                        new
                        {
                            Id = 1724662366,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "52c7c03e-6b9c-43c8-93cd-6d0c38af2520"
                        },
                        new
                        {
                            Id = 892603135,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "52c7c03e-6b9c-43c8-93cd-6d0c38af2520"
                        },
                        new
                        {
                            Id = 1377329691,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "2506ad74-1604-4a0e-bfff-d434b16344ae"
                        },
                        new
                        {
                            Id = 1146553954,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "ed1e6df8-af68-44cc-80ff-e32937583545"
                        },
                        new
                        {
                            Id = 960736301,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "ed1e6df8-af68-44cc-80ff-e32937583545"
                        },
                        new
                        {
                            Id = 169645470,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "ed1e6df8-af68-44cc-80ff-e32937583545"
                        },
                        new
                        {
                            Id = 1010093174,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "ed1e6df8-af68-44cc-80ff-e32937583545"
                        },
                        new
                        {
                            Id = 935943092,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "ed1e6df8-af68-44cc-80ff-e32937583545"
                        },
                        new
                        {
                            Id = 397427697,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "0034b642-85f5-4c06-bb37-a500e288c187"
                        },
                        new
                        {
                            Id = 2044549006,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "0034b642-85f5-4c06-bb37-a500e288c187"
                        },
                        new
                        {
                            Id = 542798954,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "1f809152-0401-4ab0-b80d-e61d046e7e30"
                        },
                        new
                        {
                            Id = 1513763553,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "1f809152-0401-4ab0-b80d-e61d046e7e30"
                        },
                        new
                        {
                            Id = 2092754607,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "1f809152-0401-4ab0-b80d-e61d046e7e30"
                        },
                        new
                        {
                            Id = 1850720950,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "1f809152-0401-4ab0-b80d-e61d046e7e30"
                        },
                        new
                        {
                            Id = 1206697884,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "1f809152-0401-4ab0-b80d-e61d046e7e30"
                        },
                        new
                        {
                            Id = 1613162362,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9"
                        },
                        new
                        {
                            Id = 1202895920,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9"
                        },
                        new
                        {
                            Id = 1753332339,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9"
                        },
                        new
                        {
                            Id = 2143496566,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9"
                        },
                        new
                        {
                            Id = 1840160016,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9"
                        },
                        new
                        {
                            Id = 441226546,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9"
                        },
                        new
                        {
                            Id = 1337468595,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "05d4176e-5516-4263-9561-750e6d07a75b"
                        },
                        new
                        {
                            Id = 303348558,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "05d4176e-5516-4263-9561-750e6d07a75b"
                        },
                        new
                        {
                            Id = 899302995,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "7265999d-da9d-461c-a372-a1090a8a62ec"
                        },
                        new
                        {
                            Id = 320226043,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "7265999d-da9d-461c-a372-a1090a8a62ec"
                        },
                        new
                        {
                            Id = 1930583941,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "7265999d-da9d-461c-a372-a1090a8a62ec"
                        },
                        new
                        {
                            Id = 882298038,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "7265999d-da9d-461c-a372-a1090a8a62ec"
                        },
                        new
                        {
                            Id = 621192772,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "b44a894a-7a09-4543-9f02-cbcfd40cbb8d"
                        },
                        new
                        {
                            Id = 588645552,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "b44a894a-7a09-4543-9f02-cbcfd40cbb8d"
                        },
                        new
                        {
                            Id = 399835112,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "8de033fe-d7c2-4375-9e49-d7387fe86153"
                        },
                        new
                        {
                            Id = 259075146,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "8de033fe-d7c2-4375-9e49-d7387fe86153"
                        },
                        new
                        {
                            Id = 351971416,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "8de033fe-d7c2-4375-9e49-d7387fe86153"
                        },
                        new
                        {
                            Id = 2114494684,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "8de033fe-d7c2-4375-9e49-d7387fe86153"
                        },
                        new
                        {
                            Id = 15717488,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "8de033fe-d7c2-4375-9e49-d7387fe86153"
                        },
                        new
                        {
                            Id = 1131251016,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084"
                        },
                        new
                        {
                            Id = 1357111178,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084"
                        },
                        new
                        {
                            Id = 1452189078,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084"
                        },
                        new
                        {
                            Id = 557503203,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084"
                        },
                        new
                        {
                            Id = 1702615242,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084"
                        },
                        new
                        {
                            Id = 1714360514,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084"
                        },
                        new
                        {
                            Id = 2081992517,
                            ClaimType = "BossClaim",
                            ClaimValue = "BossClaim",
                            UserId = "eda12e6b-c0da-4b5c-b5df-accdc0d91847"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b3023d3d-0a25-43ac-ba10-3815be222227",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "775134f4-446d-4393-a01d-8e52bd08ff78",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "906f6fc5-68ee-431b-be2e-2545682da6bd",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "c9af9594-c82f-4069-84eb-4d3793d987b9",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "d23163db-be3e-4fd5-a5da-2f72c768c05a",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "dba21b20-7551-488a-bb08-40f034e0b475",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "3f6a3f23-4c49-4fc9-9c5c-1ec226cf3a4a",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "67b764c8-35e7-462a-95e6-b39f2291c4fe",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "40dee089-43c6-4781-b39c-b320375a0f10",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "97d4c05f-c0a0-475a-9ba5-7d027d193c60",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "c1713cd1-099d-4de3-bd55-11192ec724ad",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "8cef2ae9-c0d2-4ab5-8646-429c68e7cdfc",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "8021b9a7-dca8-4940-b587-3fb85064c8a1",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "aef95f03-48d8-4397-b0c3-3b5b09f8375f",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "8e39a8f9-830a-4cfc-bbc1-462b84c85b71",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "569e6ec9-987b-484d-bfde-b393fed2b933",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "ca54a240-4d1e-4a8a-ac34-3fad5c5c5fc2",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "149a9b6c-a589-4a22-82f0-e655a84210ee",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "71827788-34d5-458b-b030-99c0fa21dd42",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "52c7c03e-6b9c-43c8-93cd-6d0c38af2520",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "2506ad74-1604-4a0e-bfff-d434b16344ae",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "ed1e6df8-af68-44cc-80ff-e32937583545",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "0034b642-85f5-4c06-bb37-a500e288c187",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "1f809152-0401-4ab0-b80d-e61d046e7e30",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "bd552e5c-2adb-4974-aecc-43bfaf14fed9",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "05d4176e-5516-4263-9561-750e6d07a75b",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "7265999d-da9d-461c-a372-a1090a8a62ec",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "b44a894a-7a09-4543-9f02-cbcfd40cbb8d",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "8de033fe-d7c2-4375-9e49-d7387fe86153",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "2ae52980-9c9e-4391-adf6-0390a3f82084",
                            RoleId = "509e6302-eac5-42e3-8ed7-f542f6579487"
                        },
                        new
                        {
                            UserId = "eda12e6b-c0da-4b5c-b5df-accdc0d91847",
                            RoleId = "f6ed4a0d-9d62-43dd-8b22-004a142bc227"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("UserEntityId");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<string>");

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "f6ed4a0d-9d62-43dd-8b22-004a142bc227",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "e08fdc8a-076a-4498-a86c-eb26bf127458",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        },
                        new
                        {
                            Id = "509e6302-eac5-42e3-8ed7-f542f6579487",
                            Name = "Pooper",
                            NormalizedName = "POOPER"
                        },
                        new
                        {
                            Id = "39eb544e-2aa1-447c-8c2f-157fef66f532",
                            Name = "Reviwer",
                            NormalizedName = "REVIWER"
                        },
                        new
                        {
                            Id = "82d36c38-b206-4709-b2e4-434599768621",
                            Name = "Maker",
                            NormalizedName = "MAKER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Auh.Entities.UserEntity", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
