// <auto-generated />
using System;
using Data.IdentityDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityDb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Auh.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AmountOfPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "91529783-f59f-46e6-a909-e7019b5c7008",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "50e20e45-e130-4654-a631-f64dfd3d174c",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-020@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-0",
                            PasswordHash = "AQAAAAIAAYagAAAAEPjoTfNd/m9NeX+P3+S1nIAGXyvQOmbTW5RqMMeuvjMFlnjB9ZShlDbarlNXDgbMxQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "3949a3ca-624f-4d47-81b6-62fa6ef917e8",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-0"
                        },
                        new
                        {
                            Id = "763379f8-0e23-4ce5-b43a-cec33eac5a32",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "779695b8-d8e3-4b4b-80e2-bca934e4b5dc",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-120@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-1",
                            PasswordHash = "AQAAAAIAAYagAAAAEB8qJ1cNNGCp4UsTHp0IfCwtH1OK12Ny2Eo5mwAvH0wX/EFXgFu5fFY6shV4OQIgSw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "b21e3721-c4ab-49fa-ad8e-f0e1d1fb2d50",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-1"
                        },
                        new
                        {
                            Id = "df55044b-3e70-4914-9b12-a789938eb7d9",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "515672b7-3eb8-4770-976c-27a0d14cb3ec",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-220@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-2",
                            PasswordHash = "AQAAAAIAAYagAAAAEAgV5Fcua9CTutvnY94kI6xSNgmaCUreE7dzC+Sv1NNwrUx0YpTwxVRpR6N1zQGnwQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "be46f58b-3b56-457b-8ece-8dc16d6a0843",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-2"
                        },
                        new
                        {
                            Id = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "c632c02a-400f-4878-bd8a-c5e15a3c14f5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-320@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-3",
                            PasswordHash = "AQAAAAIAAYagAAAAEDoOMdyQifwZ+wvF6/XH/E2XfsBzeCidhEIZTD6iVy8LKCgE05rNpJe/PkUmp95VXw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "a4d9e2c0-6d41-4590-a5ad-ec5227c464cb",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-3"
                        },
                        new
                        {
                            Id = "b745f30f-098c-4fc4-80ed-350c9e86e281",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "ad8469bd-5ed0-4c80-bb42-6fcdfbcbf0ce",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-420@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-4",
                            PasswordHash = "AQAAAAIAAYagAAAAEFH2C0mdMejXFBo0JwNDFUqfjdOGTHYziwV5ZXWOecWcKL0esUtEA1r4zBFV9bhfmQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "b242c69f-f801-4ec7-9862-fb3bfeae0c21",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-4"
                        },
                        new
                        {
                            Id = "14ac3876-cdfe-421e-87f5-7e25049290a7",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "8ceec6f2-c53e-41d0-8d26-487d201cbf49",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-520@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-5",
                            PasswordHash = "AQAAAAIAAYagAAAAEBqGnNrfLtJoezWEWgbs0mET7rRESUlD4v075ahphpfPAYj028AlqB2AHAOTOtWKnQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "eefb0c4a-385f-4fb0-81ba-457c8c6c1144",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-5"
                        },
                        new
                        {
                            Id = "fa85c792-8b69-4d03-ade7-1800fcf5aa55",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "29e50205-6b98-4b4e-98a7-d99da5f1793d",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-620@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-6",
                            PasswordHash = "AQAAAAIAAYagAAAAEKgcL5zjBeu6RHwyRJfDrKOR2yzOZZ2OixymYKSP/OEinYu6AVRECKKgSo4Og9W7mg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "1adcd8fb-c11b-44ab-97c4-d45e21438bc4",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-6"
                        },
                        new
                        {
                            Id = "74fc2a57-1944-46e3-888f-916c50ea5a47",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "a40d6852-ce26-44b5-bf56-cbb926cd42b5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-720@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-7",
                            PasswordHash = "AQAAAAIAAYagAAAAEF7jdHBO9YYNtL7DJha/L0scAFieblvxfJQQcXtSR5DkEiWropT0i6HvVRL98WkqSA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "52af036b-1fa7-49d3-a633-393663b28674",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-7"
                        },
                        new
                        {
                            Id = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "2f371f38-cf51-4895-a3f3-4b9d33bfccee",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-820@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-8",
                            PasswordHash = "AQAAAAIAAYagAAAAEIONuwk6bYj2UbBg+D2BxLjKUOBd0GxnUyQghGZHPExZPmBiY/1/lTWP8EOWZXSiPw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "2ab71807-bb39-447d-a283-88985475a85f",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-8"
                        },
                        new
                        {
                            Id = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "eeb055ac-aa14-490d-8764-9bc0acea0545",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-920@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-9",
                            PasswordHash = "AQAAAAIAAYagAAAAEI09FoEE1IP1iDUfdh2VtzML4ApRXBRr4uTpjaYzjOBA/5+ydK8TPsnWSHkhT0Bw9Q==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "9e9d08a4-866e-440c-827c-488ddcfde151",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-9"
                        },
                        new
                        {
                            Id = "0f71294b-6eed-4555-a993-17ec66922612",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "b7c78510-4a68-4492-8231-7150349be61d",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1020@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-10",
                            PasswordHash = "AQAAAAIAAYagAAAAEGeSj+DB0wGc3AO+HfgIs4HbxJA5mK/ta4uJ67naTE4y+vbRfJ+u2gLolPTD72FlsQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "98b2bc09-cccf-4702-96e7-7877bff5642b",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-10"
                        },
                        new
                        {
                            Id = "7b56b797-10e7-4642-8c56-7d00fa89f265",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "2feb0619-5727-48e7-94a1-4828822b69f6",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-1120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-1120@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-11",
                            PasswordHash = "AQAAAAIAAYagAAAAEENlE/Yj7VIEUeo4W+VriWKDrTsLhM950XlvAhfntOwrUGqWBrxwFNvH5AzfLW1g6w==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "6b867312-86dc-40ce-b3c9-c471c6c65d7a",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-11"
                        },
                        new
                        {
                            Id = "b20de05d-fd8b-4215-9f59-909ab9bf653b",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "e0f0bb1d-59c1-4c50-a121-986819a096c8",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-1220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-1220@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-12",
                            PasswordHash = "AQAAAAIAAYagAAAAEGbxsNlfAtMKWBUo2Se1SzxM6AKikSKpWOGhjsbwrKjQItmIh2mjzo/Ky36fDDBAaw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "bc254010-3469-49b4-8943-f784d399b98b",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-12"
                        },
                        new
                        {
                            Id = "fef98756-111e-4405-b117-4d39fce23d0a",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "c9be83f9-d011-46f9-b3a9-88f290822081",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1320@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-13",
                            PasswordHash = "AQAAAAIAAYagAAAAEMdaKNc9gwwpA9ROfdNoTBBnxBMNPEkiyEFbpE6tSu3LAZXrgiMD8vdkvF9AmTSnpA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "572f4d6b-b79a-49f9-a389-8b55a3f8629f",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-13"
                        },
                        new
                        {
                            Id = "5e4676c9-5751-46a8-9194-1d5411648228",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "042e02f3-2047-465f-ab6d-66207c1979c5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-1420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-1420@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-14",
                            PasswordHash = "AQAAAAIAAYagAAAAELVpVlSv0H3jj+u0xM5WP5h3Qut/BROFgkmM4Se0ewVJRbe25P/MDDucdCCiDJ3rHA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "ffd74e00-398b-4563-a71f-0e59647da65e",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-14"
                        },
                        new
                        {
                            Id = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "ca982971-cddc-46e7-8f49-0e5d0ab0ba79",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1520@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-15",
                            PasswordHash = "AQAAAAIAAYagAAAAEPV5vK2woMpz2DOcK2rDeRrfI7EXc1KfgPl2bAfprbGvxjniqs2h9ko96h0wJqBk/g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "ee06167c-d728-408d-ac8d-298147d5350c",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-15"
                        },
                        new
                        {
                            Id = "e152e4c7-cec2-4160-9103-d0622d4b5ab5",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "a621b009-7bcc-41e5-8c24-6cb802cabd1d",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1620@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-16",
                            PasswordHash = "AQAAAAIAAYagAAAAENmonczxItGWJLPX4VIs5m5jLKDbKX1TZEw3MaHr8WYb4ia+flRKfewQoz3tUdbFtw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "008b2a03-b13c-47fd-9928-941f81732270",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-16"
                        },
                        new
                        {
                            Id = "4067d998-9b4f-4941-97c4-7cc3984731fe",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "66df3360-1ea4-4821-a72b-a5c222e41a82",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-1720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-1720@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-17",
                            PasswordHash = "AQAAAAIAAYagAAAAEJVq2RzwtNk+r+2JMLCJpSBxupPm0WgmcK8ElaAb3gke2pomuGx/pvWNhhylUOIyHA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "330b26ff-8526-497e-b660-bea45206f1e5",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-17"
                        },
                        new
                        {
                            Id = "d51c0cb1-016f-4573-93bb-9e4a25a51042",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "cbb4929e-71b7-4ac0-9b4c-5eb49baf579e",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-1820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-1820@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-18",
                            PasswordHash = "AQAAAAIAAYagAAAAEMpufXoRVSvVG4SmzMtnUKvtYh5T/xCvM47Nk4i+XFhTrUVhhl/e6SEsdVlbQ7/wbQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "6c8ca6e8-429a-456b-8594-78afba846ad3",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-18"
                        },
                        new
                        {
                            Id = "8678ad5a-b93d-4220-8914-2958a96fe643",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "c05ac265-79d4-4a7e-91fd-d9dd779c2386",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-1920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-1920@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-19",
                            PasswordHash = "AQAAAAIAAYagAAAAEEgNcUR0SuVinvQgauy3MW9r/DUgYpytts6gqj/dmEVW6OhANwyawbzChmKpSkgPCA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "c43f9d5f-72e8-4650-8a1a-013e3033632c",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-19"
                        },
                        new
                        {
                            Id = "cb428034-74ac-489f-a6d1-62c48e6328a7",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "28c0830e-0b77-4426-9a3b-53cb2f80d382",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-2020@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-2020@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-20",
                            PasswordHash = "AQAAAAIAAYagAAAAEOZ1zGh45zRBvdWWV+ihQ2BVPt7EIvicS+XuHRdBHh2iCTjb9PZelB9dPsSxURXIeQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "080c8f67-42f4-4fe3-bfa9-eaca88928c31",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-20"
                        },
                        new
                        {
                            Id = "0c1df73d-271f-4785-9a9a-ce8534d96dc1",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "7bc574dd-9b97-4014-a370-4e8d10306640",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "VladBlack-2120@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBLACK-2120@MAIL.RU",
                            NormalizedUserName = "VLADBLACK-21",
                            PasswordHash = "AQAAAAIAAYagAAAAEMp4NbJ5SE0mkKfqAhediyfwaH47LFzKAHwHf4Wm9TnztAMzoWGa0ws6lsGowqFWug==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "1bef70bc-e5c1-4666-b158-66ea808e8e3a",
                            TwoFactorEnabled = false,
                            UserName = "VladBlack-21"
                        },
                        new
                        {
                            Id = "60b78d95-67f6-43ea-958c-ba3acf3f9267",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "f959d1e9-f226-4b53-854b-98ca565e68ba",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-2220@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-2220@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-22",
                            PasswordHash = "AQAAAAIAAYagAAAAEFv2E3VzP91qSeDYBofIWEeNRoKmjlbXc+fBOklu7X4sDM+jhoVxy5pmqUnuTbLKhQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "3378d89e-6688-4588-9dfc-d3d5dd8fc5be",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-22"
                        },
                        new
                        {
                            Id = "78ab86e4-ff9d-41ca-ab0a-94867253bffd",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "a94c2891-a0f0-4031-91dc-567b24795396",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2320@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2320@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-23",
                            PasswordHash = "AQAAAAIAAYagAAAAEKem9XbEfoTOZ+9LhpiGBkrL7xoc5AS5DEoFNvhX1xzLs0vHuRvmRqzx3KxK0WyE7g==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "c8b8ea71-2c90-40aa-a6f5-fda4793cb0b0",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-23"
                        },
                        new
                        {
                            Id = "a95a9af9-1f67-4c79-b559-c87ec054ff60",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "bb8b1f41-d4d0-4874-8c67-3937ce36c034",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2420@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2420@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-24",
                            PasswordHash = "AQAAAAIAAYagAAAAENwZ1bAWfNbQ0Lner+oZLeD6IjAPSl+LOBn3CB9qNJZpbQ5fwJ3mbqKQjHFrGq5H6A==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "760b0f97-5526-4ce7-b3b2-c2e3f243ad40",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-24"
                        },
                        new
                        {
                            Id = "31213f3b-9ff2-46ab-a055-c1b10c0ab680",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "bbdaea35-7da8-4dbc-9bee-db282743f3e5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "GregorPiha-2520@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GREGORPIHA-2520@MAIL.RU",
                            NormalizedUserName = "GREGORPIHA-25",
                            PasswordHash = "AQAAAAIAAYagAAAAEKJIy96vZZm+47M5ym8o+O5BSdCK8/VBhRaaYJum6572m/9aqMh7zaFgBvmg+hLH4Q==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "f7c90aae-5cef-4de2-a11d-d94a5bb984c7",
                            TwoFactorEnabled = false,
                            UserName = "GregorPiha-25"
                        },
                        new
                        {
                            Id = "c7a156dc-7994-4782-91b7-4eb67587fe6f",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "3e7d9ef2-6174-4e42-9262-783be1a12e12",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaKareva-2620@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYAKAREVA-2620@MAIL.RU",
                            NormalizedUserName = "NASTYAKAREVA-26",
                            PasswordHash = "AQAAAAIAAYagAAAAEOu8lf7B/VDX95eUrKivgbdirR6HWo2iTTjL/2Ea41ClDyoxIavlGbgkhZ2irGBwGg==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "2d9f1f72-d086-439b-9c7c-3ac917993439",
                            TwoFactorEnabled = false,
                            UserName = "NastyaKareva-26"
                        },
                        new
                        {
                            Id = "73231bcc-029a-403e-933d-d13277a16ce7",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "220ae0f6-9b50-4e37-80d8-4c647408f3f7",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "NastyaBocharnikova-2720@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NASTYABOCHARNIKOVA-2720@MAIL.RU",
                            NormalizedUserName = "NASTYABOCHARNIKOVA-27",
                            PasswordHash = "AQAAAAIAAYagAAAAECbajo5eSlyjEjHP4x0WEQMyTLVGKht2tNFnrS47P6AiPBNUU1hPia35x7hpfDC0WA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "7dc8df43-84f7-4520-ae92-8c786e065673",
                            TwoFactorEnabled = false,
                            UserName = "NastyaBocharnikova-27"
                        },
                        new
                        {
                            Id = "6eae61a9-18c4-4fa7-83e1-98c2bfb5c0b1",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "637f8732-89a8-496a-a01d-ddef5a665ecb",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "AdrewRojer-2820@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADREWROJER-2820@MAIL.RU",
                            NormalizedUserName = "ADREWROJER-28",
                            PasswordHash = "AQAAAAIAAYagAAAAEGJ9yH5T7rPi+7NjP5+nWnyJ/HoBLAsN3M2Rs3T4NQWE1UakEZeC3Zv9pLcVAXXI/w==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "6b18fef7-6ae5-4b1d-84a8-398b9dc49ea2",
                            TwoFactorEnabled = false,
                            UserName = "AdrewRojer-28"
                        },
                        new
                        {
                            Id = "17904617-974d-42ec-acb7-8bbf97fc0b93",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "68a5dfbc-c9c3-4e8c-b66b-9bfe31e4e0f5",
                            Description = "I am a pooper! Poo poo poo!!!",
                            Email = "SanchoLeaver-2920@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANCHOLEAVER-2920@MAIL.RU",
                            NormalizedUserName = "SANCHOLEAVER-29",
                            PasswordHash = "AQAAAAIAAYagAAAAEHFVuUmO9BFwwEUcNWiVxzmrDnfa5Z3yID31ZYbcE2odm8aOe9Lh5UWNZp/vW02ZAw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            SecurityStamp = "ce70e521-b371-4a2c-8d5a-258449f093e2",
                            TwoFactorEnabled = false,
                            UserName = "SanchoLeaver-29"
                        },
                        new
                        {
                            Id = "79277431-92a5-4134-80dc-5dcdb7e4d969",
                            AccessFailedCount = 0,
                            AmountOfPoints = 0,
                            ConcurrencyStamp = "13ba7c5b-9801-44a7-8535-cc438776e557",
                            Description = "I am the admin! Call me the Boss!!!",
                            Email = "VladBalkar20@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADBALKAR20@MAIL.RU",
                            NormalizedUserName = "VLADBALKAR",
                            PasswordHash = "AQAAAAIAAYagAAAAEKJ8WpcvkLWG1R1lrtwLfKy7jFDL7Y8pL0B1xinFWD6THsHCVNfGVfvzTxsZjAsiJA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            RoleId = "ede0e41a-7e0c-4eb8-aaba-85bb2872dd63",
                            SecurityStamp = "930c655b-2eba-4dc3-917a-b0365ebe6ff9",
                            TwoFactorEnabled = false,
                            UserName = "VladBalkar"
                        });
                });

            modelBuilder.Entity("Core.Base.DataBase.Entities.PooperEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AmountOfPoops")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Poopers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 639298895,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "91529783-f59f-46e6-a909-e7019b5c7008"
                        },
                        new
                        {
                            Id = 863353732,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "91529783-f59f-46e6-a909-e7019b5c7008"
                        },
                        new
                        {
                            Id = 1863288295,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "91529783-f59f-46e6-a909-e7019b5c7008"
                        },
                        new
                        {
                            Id = 1878142988,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "91529783-f59f-46e6-a909-e7019b5c7008"
                        },
                        new
                        {
                            Id = 1072440820,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "91529783-f59f-46e6-a909-e7019b5c7008"
                        },
                        new
                        {
                            Id = 1879190156,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "763379f8-0e23-4ce5-b43a-cec33eac5a32"
                        },
                        new
                        {
                            Id = 493361568,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "763379f8-0e23-4ce5-b43a-cec33eac5a32"
                        },
                        new
                        {
                            Id = 460319820,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "df55044b-3e70-4914-9b12-a789938eb7d9"
                        },
                        new
                        {
                            Id = 1777956039,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "df55044b-3e70-4914-9b12-a789938eb7d9"
                        },
                        new
                        {
                            Id = 1508281739,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "df55044b-3e70-4914-9b12-a789938eb7d9"
                        },
                        new
                        {
                            Id = 1136414074,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "df55044b-3e70-4914-9b12-a789938eb7d9"
                        },
                        new
                        {
                            Id = 1114354845,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636"
                        },
                        new
                        {
                            Id = 924208317,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636"
                        },
                        new
                        {
                            Id = 56732682,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636"
                        },
                        new
                        {
                            Id = 1052781288,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636"
                        },
                        new
                        {
                            Id = 287040200,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636"
                        },
                        new
                        {
                            Id = 1071981067,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "b745f30f-098c-4fc4-80ed-350c9e86e281"
                        },
                        new
                        {
                            Id = 1519554160,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "b745f30f-098c-4fc4-80ed-350c9e86e281"
                        },
                        new
                        {
                            Id = 1649631468,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "b745f30f-098c-4fc4-80ed-350c9e86e281"
                        },
                        new
                        {
                            Id = 2115245597,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "14ac3876-cdfe-421e-87f5-7e25049290a7"
                        },
                        new
                        {
                            Id = 977441889,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "14ac3876-cdfe-421e-87f5-7e25049290a7"
                        },
                        new
                        {
                            Id = 35959751,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "14ac3876-cdfe-421e-87f5-7e25049290a7"
                        },
                        new
                        {
                            Id = 678219776,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "14ac3876-cdfe-421e-87f5-7e25049290a7"
                        },
                        new
                        {
                            Id = 763827891,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55"
                        },
                        new
                        {
                            Id = 1951422034,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55"
                        },
                        new
                        {
                            Id = 2032718909,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55"
                        },
                        new
                        {
                            Id = 2069931733,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55"
                        },
                        new
                        {
                            Id = 1225004237,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55"
                        },
                        new
                        {
                            Id = 1785933454,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55"
                        },
                        new
                        {
                            Id = 1581011563,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "74fc2a57-1944-46e3-888f-916c50ea5a47"
                        },
                        new
                        {
                            Id = 337426543,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "74fc2a57-1944-46e3-888f-916c50ea5a47"
                        },
                        new
                        {
                            Id = 658819874,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "74fc2a57-1944-46e3-888f-916c50ea5a47"
                        },
                        new
                        {
                            Id = 1475130206,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "74fc2a57-1944-46e3-888f-916c50ea5a47"
                        },
                        new
                        {
                            Id = 1077780533,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1"
                        },
                        new
                        {
                            Id = 1410894884,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1"
                        },
                        new
                        {
                            Id = 298528646,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1"
                        },
                        new
                        {
                            Id = 221733946,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1"
                        },
                        new
                        {
                            Id = 1787781713,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1"
                        },
                        new
                        {
                            Id = 1081868784,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1"
                        },
                        new
                        {
                            Id = 1409977444,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af"
                        },
                        new
                        {
                            Id = 1396078129,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af"
                        },
                        new
                        {
                            Id = 2039971813,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af"
                        },
                        new
                        {
                            Id = 1188009155,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af"
                        },
                        new
                        {
                            Id = 951977103,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af"
                        },
                        new
                        {
                            Id = 1053484248,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af"
                        },
                        new
                        {
                            Id = 780428214,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "0f71294b-6eed-4555-a993-17ec66922612"
                        },
                        new
                        {
                            Id = 675636236,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "0f71294b-6eed-4555-a993-17ec66922612"
                        },
                        new
                        {
                            Id = 1843385702,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "0f71294b-6eed-4555-a993-17ec66922612"
                        },
                        new
                        {
                            Id = 1709567218,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "0f71294b-6eed-4555-a993-17ec66922612"
                        },
                        new
                        {
                            Id = 1108320132,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "0f71294b-6eed-4555-a993-17ec66922612"
                        },
                        new
                        {
                            Id = 2951150,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "7b56b797-10e7-4642-8c56-7d00fa89f265"
                        },
                        new
                        {
                            Id = 28092540,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "7b56b797-10e7-4642-8c56-7d00fa89f265"
                        },
                        new
                        {
                            Id = 1913763672,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "b20de05d-fd8b-4215-9f59-909ab9bf653b"
                        },
                        new
                        {
                            Id = 1751906625,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "b20de05d-fd8b-4215-9f59-909ab9bf653b"
                        },
                        new
                        {
                            Id = 283851094,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "b20de05d-fd8b-4215-9f59-909ab9bf653b"
                        },
                        new
                        {
                            Id = 1275438208,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "fef98756-111e-4405-b117-4d39fce23d0a"
                        },
                        new
                        {
                            Id = 356832734,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "fef98756-111e-4405-b117-4d39fce23d0a"
                        },
                        new
                        {
                            Id = 1537633819,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "fef98756-111e-4405-b117-4d39fce23d0a"
                        },
                        new
                        {
                            Id = 1269278859,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "fef98756-111e-4405-b117-4d39fce23d0a"
                        },
                        new
                        {
                            Id = 55888542,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228"
                        },
                        new
                        {
                            Id = 1214045480,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228"
                        },
                        new
                        {
                            Id = 998515681,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228"
                        },
                        new
                        {
                            Id = 489030695,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228"
                        },
                        new
                        {
                            Id = 1656952277,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228"
                        },
                        new
                        {
                            Id = 1661539475,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228"
                        },
                        new
                        {
                            Id = 1675213763,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8"
                        },
                        new
                        {
                            Id = 1591382127,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8"
                        },
                        new
                        {
                            Id = 165542149,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8"
                        },
                        new
                        {
                            Id = 1241273842,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8"
                        },
                        new
                        {
                            Id = 1140129437,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8"
                        },
                        new
                        {
                            Id = 159488245,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "e152e4c7-cec2-4160-9103-d0622d4b5ab5"
                        },
                        new
                        {
                            Id = 1533929501,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "e152e4c7-cec2-4160-9103-d0622d4b5ab5"
                        },
                        new
                        {
                            Id = 678754087,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "e152e4c7-cec2-4160-9103-d0622d4b5ab5"
                        },
                        new
                        {
                            Id = 1153635371,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "e152e4c7-cec2-4160-9103-d0622d4b5ab5"
                        },
                        new
                        {
                            Id = 329027892,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "e152e4c7-cec2-4160-9103-d0622d4b5ab5"
                        },
                        new
                        {
                            Id = 1052346715,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "4067d998-9b4f-4941-97c4-7cc3984731fe"
                        },
                        new
                        {
                            Id = 829634256,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "4067d998-9b4f-4941-97c4-7cc3984731fe"
                        },
                        new
                        {
                            Id = 518038319,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "4067d998-9b4f-4941-97c4-7cc3984731fe"
                        },
                        new
                        {
                            Id = 672190182,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "4067d998-9b4f-4941-97c4-7cc3984731fe"
                        },
                        new
                        {
                            Id = 66443067,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "4067d998-9b4f-4941-97c4-7cc3984731fe"
                        },
                        new
                        {
                            Id = 92369021,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "d51c0cb1-016f-4573-93bb-9e4a25a51042"
                        },
                        new
                        {
                            Id = 57688462,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "d51c0cb1-016f-4573-93bb-9e4a25a51042"
                        },
                        new
                        {
                            Id = 799583,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "d51c0cb1-016f-4573-93bb-9e4a25a51042"
                        },
                        new
                        {
                            Id = 2005939682,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "d51c0cb1-016f-4573-93bb-9e4a25a51042"
                        },
                        new
                        {
                            Id = 518746848,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "8678ad5a-b93d-4220-8914-2958a96fe643"
                        },
                        new
                        {
                            Id = 1990055372,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "cb428034-74ac-489f-a6d1-62c48e6328a7"
                        },
                        new
                        {
                            Id = 1227787672,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "cb428034-74ac-489f-a6d1-62c48e6328a7"
                        },
                        new
                        {
                            Id = 420847719,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "0c1df73d-271f-4785-9a9a-ce8534d96dc1"
                        },
                        new
                        {
                            Id = 1869681260,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "0c1df73d-271f-4785-9a9a-ce8534d96dc1"
                        },
                        new
                        {
                            Id = 1334859437,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "0c1df73d-271f-4785-9a9a-ce8534d96dc1"
                        },
                        new
                        {
                            Id = 483033475,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "60b78d95-67f6-43ea-958c-ba3acf3f9267"
                        },
                        new
                        {
                            Id = 901439219,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "60b78d95-67f6-43ea-958c-ba3acf3f9267"
                        },
                        new
                        {
                            Id = 1997342579,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "60b78d95-67f6-43ea-958c-ba3acf3f9267"
                        },
                        new
                        {
                            Id = 78062952,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "60b78d95-67f6-43ea-958c-ba3acf3f9267"
                        },
                        new
                        {
                            Id = 795873939,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "78ab86e4-ff9d-41ca-ab0a-94867253bffd"
                        },
                        new
                        {
                            Id = 2010922972,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "78ab86e4-ff9d-41ca-ab0a-94867253bffd"
                        },
                        new
                        {
                            Id = 465842678,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "78ab86e4-ff9d-41ca-ab0a-94867253bffd"
                        },
                        new
                        {
                            Id = 1117231971,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "78ab86e4-ff9d-41ca-ab0a-94867253bffd"
                        },
                        new
                        {
                            Id = 1626784383,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "78ab86e4-ff9d-41ca-ab0a-94867253bffd"
                        },
                        new
                        {
                            Id = 41823720,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "a95a9af9-1f67-4c79-b559-c87ec054ff60"
                        },
                        new
                        {
                            Id = 131332613,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "a95a9af9-1f67-4c79-b559-c87ec054ff60"
                        },
                        new
                        {
                            Id = 1460432596,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "a95a9af9-1f67-4c79-b559-c87ec054ff60"
                        },
                        new
                        {
                            Id = 299806558,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "a95a9af9-1f67-4c79-b559-c87ec054ff60"
                        },
                        new
                        {
                            Id = 408252702,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "a95a9af9-1f67-4c79-b559-c87ec054ff60"
                        },
                        new
                        {
                            Id = 1293413404,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680"
                        },
                        new
                        {
                            Id = 2024970530,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680"
                        },
                        new
                        {
                            Id = 210120708,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680"
                        },
                        new
                        {
                            Id = 588757362,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680"
                        },
                        new
                        {
                            Id = 825907669,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680"
                        },
                        new
                        {
                            Id = 1887565804,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680"
                        },
                        new
                        {
                            Id = 1871744435,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f"
                        },
                        new
                        {
                            Id = 298020144,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f"
                        },
                        new
                        {
                            Id = 1623712431,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f"
                        },
                        new
                        {
                            Id = 1787481124,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f"
                        },
                        new
                        {
                            Id = 304008610,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f"
                        },
                        new
                        {
                            Id = 1058339145,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f"
                        },
                        new
                        {
                            Id = 2098895574,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "73231bcc-029a-403e-933d-d13277a16ce7"
                        },
                        new
                        {
                            Id = 1031210755,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "73231bcc-029a-403e-933d-d13277a16ce7"
                        },
                        new
                        {
                            Id = 1626049072,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Front",
                            UserId = "73231bcc-029a-403e-933d-d13277a16ce7"
                        },
                        new
                        {
                            Id = 861744320,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "73231bcc-029a-403e-933d-d13277a16ce7"
                        },
                        new
                        {
                            Id = 1185580400,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "6eae61a9-18c4-4fa7-83e1-98c2bfb5c0b1"
                        },
                        new
                        {
                            Id = 1237514953,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "6eae61a9-18c4-4fa7-83e1-98c2bfb5c0b1"
                        },
                        new
                        {
                            Id = 1964216306,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lead",
                            UserId = "6eae61a9-18c4-4fa7-83e1-98c2bfb5c0b1"
                        },
                        new
                        {
                            Id = 1916608198,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Stinky",
                            UserId = "17904617-974d-42ec-acb7-8bbf97fc0b93"
                        },
                        new
                        {
                            Id = 493886181,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Back",
                            UserId = "17904617-974d-42ec-acb7-8bbf97fc0b93"
                        },
                        new
                        {
                            Id = 927060055,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Lol",
                            UserId = "17904617-974d-42ec-acb7-8bbf97fc0b93"
                        },
                        new
                        {
                            Id = 704618941,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dev",
                            UserId = "17904617-974d-42ec-acb7-8bbf97fc0b93"
                        },
                        new
                        {
                            Id = 197992319,
                            ClaimType = "SharerClaim",
                            ClaimValue = "Dba",
                            UserId = "17904617-974d-42ec-acb7-8bbf97fc0b93"
                        },
                        new
                        {
                            Id = 602634309,
                            ClaimType = "BossClaim",
                            ClaimValue = "BossClaim",
                            UserId = "79277431-92a5-4134-80dc-5dcdb7e4d969"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "91529783-f59f-46e6-a909-e7019b5c7008",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "763379f8-0e23-4ce5-b43a-cec33eac5a32",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "df55044b-3e70-4914-9b12-a789938eb7d9",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "5b5fd5c5-f70d-4eb7-97bb-7012f5239636",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "b745f30f-098c-4fc4-80ed-350c9e86e281",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "14ac3876-cdfe-421e-87f5-7e25049290a7",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "fa85c792-8b69-4d03-ade7-1800fcf5aa55",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "74fc2a57-1944-46e3-888f-916c50ea5a47",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "dd68aa51-d250-4c9d-9b3f-ec857abfefb1",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "ad9178c0-e81b-49d4-98f9-b51cfeb6c2af",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "0f71294b-6eed-4555-a993-17ec66922612",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "7b56b797-10e7-4642-8c56-7d00fa89f265",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "b20de05d-fd8b-4215-9f59-909ab9bf653b",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "fef98756-111e-4405-b117-4d39fce23d0a",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "5e4676c9-5751-46a8-9194-1d5411648228",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "52ab31cf-0a12-46e8-8e76-dceb4e314ed8",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "e152e4c7-cec2-4160-9103-d0622d4b5ab5",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "4067d998-9b4f-4941-97c4-7cc3984731fe",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "d51c0cb1-016f-4573-93bb-9e4a25a51042",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "8678ad5a-b93d-4220-8914-2958a96fe643",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "cb428034-74ac-489f-a6d1-62c48e6328a7",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "0c1df73d-271f-4785-9a9a-ce8534d96dc1",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "60b78d95-67f6-43ea-958c-ba3acf3f9267",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "78ab86e4-ff9d-41ca-ab0a-94867253bffd",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "a95a9af9-1f67-4c79-b559-c87ec054ff60",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "31213f3b-9ff2-46ab-a055-c1b10c0ab680",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "c7a156dc-7994-4782-91b7-4eb67587fe6f",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "73231bcc-029a-403e-933d-d13277a16ce7",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "6eae61a9-18c4-4fa7-83e1-98c2bfb5c0b1",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "17904617-974d-42ec-acb7-8bbf97fc0b93",
                            RoleId = "141e0978-3c9e-4074-92e5-abecffe0d99c"
                        },
                        new
                        {
                            UserId = "79277431-92a5-4134-80dc-5dcdb7e4d969",
                            RoleId = "ede0e41a-7e0c-4eb8-aaba-85bb2872dd63"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("UserEntityId");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<string>");

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "ede0e41a-7e0c-4eb8-aaba-85bb2872dd63",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "45775a85-8a62-48d0-a79a-d396f82cc551",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        },
                        new
                        {
                            Id = "141e0978-3c9e-4074-92e5-abecffe0d99c",
                            Name = "Pooper",
                            NormalizedName = "POOPER"
                        },
                        new
                        {
                            Id = "a96bf07e-3a0f-4599-985e-5040d3e0c974",
                            Name = "Reviwer",
                            NormalizedName = "REVIWER"
                        },
                        new
                        {
                            Id = "69b07d0b-8b37-43c8-91de-7a487def5118",
                            Name = "Maker",
                            NormalizedName = "MAKER"
                        });
                });

            modelBuilder.Entity("Core.Base.DataBase.Entities.PooperEntity", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Core.Auh.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Auh.Entities.UserEntity", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
